### ISSUE TITLE
URL à mettre à jour dans la partie RÉFÉRENCES

### ISSUE THREAD

**Issue by xDEADC0DE** [tifhair/tifhair-tools#12]
Le 3e lien des références, « "Communiqué" de Boulet 2009-09-17 » est en 404

il faudrait remplacer
- https://bouletcorp.com/2009/09/17/communique/
par :
- https://bouletcorp.com/notes/2009/09/16

**Comment by tifhair** [comment]
done, thanks

**Comment by tifhair** [comment]
https://github.com/tifhair/tifhair-tools/commit/f03bbe9b1ba875c3900db5170f3fda774a48b064
