### ISSUE TITLE
Référencez le site comme réutilisation

### ISSUE THREAD

**Issue by agarrone** [tifhair/tifhair-tools#8]
Bravo pour cette réutilisation qui nous a bien amusé ! 
N'hésitez pas à la référencer sur data.gouv.fr sur la base Sirene https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret je me ferrais un plaisir de la mettre en avant. Voir [le guide](https://guides.etalab.gouv.fr/reutilisation/) si besoin.

Très bonne journée, 
Antonin Garrone pour l'équipe data.gouv.fr

**Comment by tifhair** [comment]
https://www.data.gouv.fr/fr/reuses/les-coiffeurs-sont-des-blagueurs/

La fabuleuse image semble ne pas être bien acceptée sur la page https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/#community-reuses :)
